== Développement d'un smart-contract ```AddressBook```

=== Contexte
Pour rappel la délivrance du label AOP ne peut se faire que si les éleveurs
fournissant le lait et la laiterie sont tous domiciliés dans une zone
géographique précise.

Il va donc falloir disposer du lieu de chaque participant. Nous allons
simplifier cette partie en associant uniquement un code postal à chaque
participant.

Quorum ne propose pas de moyen d'associer des données à un noeud/participant. +
Nous allons donc réaliser un smart-contract ```AddressBook```. +
Ce smart-contract ne sera pas en mode *privatif* car tout le monde devra
pouvoir y accéder pour consulter le lieu de chaque établissement.

TIP: Du coup au travers de ce TP vous serez amenés à mélanger des
  smart-contracts publics avec d'autres privés !

=== Définition du smart-contract ```AddressBook```

Le premier exercice de ce TP va consister à implémenter le
smart-contract ```AddressBook```.

Afin de respecter des bonnes pratiques le code s'appuiera sur la librairie
https://openzeppelin.org/[OpenZeppelin].

La structure simplifiée du squelette de l'application sera donc la suivante :

[source,solidity,linenums]
.AddressBook.sol
----
include::../contracts/AddressBook.sol[tag=!implementation]
----
<1> On importe le smart-contract ```Ownable``` d'OpenZeppelin.
<2> Notre smart-contract hérite d'```Ownable```.
<3> Le ```mapping``` permettra de savoir quel est le code postal de chaque participant.
<4> *Cette fonctionnalité est donc à développer de votre côté !*
<5> Le smart-contract émettra un événement ```ParticipantAdded```.
<6> *Cette fonctionnalité est donc à développer de votre côté !*

TIP: L'utilisation d'un smart-contract https://ens.domains[Ethereum Name Service]
  aurait bien plus de sens pour un usage en production.

=== Implémentation du smart-contract ```AddressBook```

Le code de démarrage de cet exercice est disponible dans le repository Git. +
Récupérez ce code et installez les dépendances qui vont bien :

[source,shell]
----
git clone https://gitlab.talanlabs.com/blockchain/formation/tp-quorum.git
cd tp-quorum
git checkout exercice-01
npm install
npm install -g ganache
npm install -g truffle
npm install -g truffle-flattener
----

.Codes postaux des participants
[%header,cols=2*]
|===
|Commune
|Code postal

|Hauteluce
|73620
|Landry
|73210
|Beaufort
|73270
|Bastia
|20200
|===

La validation géographique se faisant par code postal, nous considérerons
les codes postaux suivants comme valides : ```Hauteluce```, ```Landry```, ```Beaufort```. +
A l'inverse le code postal de ```Bastia``` sera considéré comme hors de la zone
géographique du label AOP.

WARNING: Lancez Ganache (que nous utiliserons temporairement) !

Vous aurez besoin de vérifier votre fichier ```truffle-config.js```. Il devrait
contenir à minima ce contenu :

[source,javascript,linenums]
.truffle-config.js
----
include::../truffle-config.js[tags=!quorum;!cooperative]
----

Commencez par l'implémentation de la fonction ```addParticipantZipCode()```,
puis continuez avec la méthode ```checkGeoBoundaries()```.

Vous pouvez compiler et déployer dans Ganache votre smart-contract via la
commande suivante  :

[source]
----
$ truffle migrate --network ganache --reset

Compiling ./contracts/AddressBook.sol...
Compiling ./contracts/Migrations.sol...
Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
Writing artifacts to ./build/contracts

Using network 'ganache'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x8c77473a363c956470e4196b2545509e825d68219d7fcc5823fe1184c7eb5526
  Migrations: 0x32fd6757adada7b38ec95a6dbd0f13917c961c24
Saving successful migration to network...
  ... 0x0c73880fa015eeacfb0edfb1248c8b884d2432dc6bc65a074670ff9398ec47b2
Saving artifacts...
Running migration: 2_address_book.js
  Deploying AddressBook...
  ... 0xf00a590e3db8ab7f4dcf85ab4f50b89abc82c57b8f093cc438a3b77c329c8fab
  AddressBook: 0xfc6b8743d865308374dedcf9dc15a1e70d72f045
Saving successful migration to network...
  ... 0x9c499c64372cf6538aa72c11990123b392dbc905cf1fc87ad367e83fb8eca16b
Saving artifacts...
----

Pour tester le bon fonctionnement de votre implémentation, vous pouvez la
tester via la commande illustrée ci-dessous et vous devriez avoir un résultat
similaire à celui-ci si tout passe bien :

[source]
----
$ truffle test --network ganache --reset

Using network 'ganache'.

  Contract: AddressBook
    ✓ should detect geo boundaries properly (298ms)

  1 passing (336ms)
----
