== Interfaçage avec Quorum via web3

=== Contexte

Lors de ce chapitre nous allons nous concentrer sur la manière de faire des
appels aux smart-contracts.

WARNING: La mise en oeuvre qui va être faite dans ce TP est tout sauf
  représentative de ce qu'on ferait normalement. Par simplicité, nous allons
  considérer que le front-end va directement communiquer avec Quorum. +
  Une architecture plus traditionnelle serait de livrer des containers
  Docker (front-end, back-end / API, base NoSQL/cache, Quorum si pas porté par
  Kaleido, etc.) et que chaque acteur fasse tourner cette stack technique sur
  son infrastructure, Quorum étant en charge de la _synchronisation_ des données
  entre les acteurs.

.Architecture _traditionnelle_ avec des DLT
[svgbob,architecture-production,svg,align=center]
----
        ,-.                    ,-.                    ,-.
        `-'                    `-'                    `-'
        /|\                    /|\                    /|\
         |                      |                      |
        / \                    / \                    / \

         ^                      ^                      ^
         |                      |                      |
         |                      |                      |
.----- Docker ----.    .----- Docker ----.    .----- Docker ----.
|        |        |    |        |        |    |        |        |
|        v        |    |        v        |    |        v        |
|  .-----------.  |    |  .-----------.  |    |  .-----------.  |
|  | Front-end |  |    |  | Front-end |  |    |  | Front-end |  |
|  '-----------'  |    |  '-----------'  |    |  '-----------'  |
|        ^        |    |        ^        |    |        ^        |
|        |        |    |        |        |    |        |        |
|        v        |    |        v        |    |        v        |
|  .-----------.  |    |  .-----------.  |    |  .-----------.  |
|  | Back-end  |  |    |  | Back-end  |  |    |  | Back-end  |  |
|  '-----------'  |    |  '-----------'  |    |  '-----------'  |
|     ^     ^     |    |     ^     ^     |    |     ^     ^     |
|     |     |     |    |     |     |     |    |     |     |     |
|     |     v     |    |     |     v     |    |     |     v     |
|     | .-------. |    |     | .-------. |    |     | .-------. |
|     | | Cache | |    |     | | Cache | |    |     | | Cache | |
|     | '-------' |    |     | '-------' |    |     | '-------' |
|     v           |    |     v           |    |     v           |
|  .-----------.  |    |  .-----------.  |    |  .-----------.  |
|  |  Quorum   |<========>|  Quorum   |<========>|  Quorum   |  |
|  '-----------'  |    |  '-----------'  |    |  '-----------'  |
|                 |    |                 |    |                 |
`-----------------'    `-----------------'    `-----------------'
   Participant 1          Participant 2    ...   Participant n


----

Avec Ethereum et Quorum, on utilise une API nommée Web3. Il existe au moins
autant d'implémentations que de langages. Dans notre cas, vu que nous
réaliserons uniquement un front-end web directement interfaçé avec Quorum, il
nous suffit d'utiliser une librairie JavaScript.

ifdef::backend-pdf[<<<]

Rien qu'en JavaScript il existe plusieurs implémentations viables :

* https://github.com/ethereum/wiki/wiki/JavaScript-API#web3-javascript-app-api-for-02xx[web3.js 0.x]
* https://web3js.readthedocs.io/en/1.0/getting-started.html[web3.js 1.x]
* https://docs.ethers.io/ethers.js/html/[ethers.js]

Etant donné que nous utilisons déjà Truffle et qu'il fournit plusieurs
facilités de développement pour l'intégration avec un front-end ou back-end,
nous allons utiliser web3.js sur lequel Truffle s'appuie.

WARNING: Suivant la version de Truffle que vous utilisez la version de web3.js
  change. Truffle 4 utilise la version 0.9.x alors que Truffle 5 s'appuie sur
  la version 1.x.

Enfin, dans le but de simplifier le TP, nous nous _contenterons_ de technologies
simplistes pour le front-end, à savoir l'usage de https://jquery.com[jQuery].

L'usage de https://reactjs.org[React] ou https://vuejs.org[Vue.js] serait bien
plus adéquat pour une réelle application mais l'objectif de ce TP n'est pas de
former sur ces technologies et donc pour éviter trop de pré-requis un tel choix
n'est pas fait sur ce TP.
