== Déploiement des smart-contracts dans Kaleido

=== Déploiement du smart-contract ```AddressBook```

Le smart-contract ```AddressBook``` étant public, ```truffle``` peut simplement
le déployer avec la commande suivante :

[source]
----
$ truffle migrate --network cooperative <1>
Using network 'cooperative'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xd563e2af6110e0c3f1d78effc05812438beb751c79d871bbd3d06a677c899558
  Migrations: 0x8af663d571e111e57a937a811c1d96bcedbf7903
Saving successful migration to network...
  ... 0x79168c9198b532f8b2505d14858f60471871fa03e31e6a670e1000e9bf15d253
Saving artifacts...
Running migration: 2_address_book.js
  Deploying AddressBook...
  ... 0xc2e1a70958271f6af8a89256430bd8fde422c8265394ee9026ba00113e270297
  AddressBook: 0x911bc28290b1f3d5715d88b34d04d70099c97dbc <2>
Saving successful migration to network...
  ... 0xf7b986e2ec97b7061850bd285f66879615cedccd797d00e9b3cc08b22d0c5558
Saving artifacts...
----
<1> On précise que l'on veut déployer ce smart-contract via le noeud
    _cooperative_ tel que défini précédemment dans le fichier
    <<truffle-config-kaleido>>. Vu qu'aucune clause _privateFor_ n'est précisée,
    ce smart-contract est déployé de manière publique, donc accessible par tous
    les noeuds du Consortium.
<2> Adresse à laquelle le smart-contract ```AddressBook``` est déployé.


=== Ajout des participants

L````AddressBook``` précédemment déployé sur Quorum n'a pas encore été enrichi
avec les données des participants.

Outre l'adresse Ethereum et le code postal de chaque participant nous aurons
aussi besoin de l'adresse pour les transactions privées Quorum.

ifdef::backend-pdf[<<<]

Afin de simplifier cela, un script est fourni permettant de renseigner
l'```AddressBook``` à partir d'un fichier Json indiquant toutes les données
utiles.

[source,javascript,linenums]
.data/addressbook.json
----
include::../data/addressbook.json[]
----

Les modifications à apporter sont les suivantes :

1. Ligne 2, modifiez l'adresse pour qu'elle soit celle à laquelle le
  smart-contract ```AddressBook``` a été déployé sur votre environnement
  Kaleido
2. Ligne 5 (puis pour chaque participant), modifiez ```ethereum_pk``` en mettant
  à la place la valeur de ```User Accounts``` quand sur vous allez sur
  *Node Details* du noeud concerné
3. Ligne 6 (puis pour chaque participant), modifiez ```quorum_pk``` en mettant
  à la place la valeur de ```Private TX Participant``` quand vous allez sur
  *Node Details* du noeud concerné
4. Répétez les étapes 2 et 3 pour chacun des participants

ifdef::backend-pdf[<<<]

Une fois que ce fichier est correctement renseigné, lancez la commande
suivante :

[source,shell]
----
truffle exec --network cooperative populate-addressbook.js
----

Cela va demander à Truffle de faire des appels à la
méthode ```addParticipantZipCode()``` pour chaque participant du fichier et
lancer ces mises à jour en tant que la coopérative (la seule autorisée à faire
de tels ajouts pour rappel).

Vous devriez avoir un résultat similaire à celui ci :

[source,shell]
----
Using network 'cooperative'.

Getting deployed version of AddressBook at address '0x9d698b0c93a11840e9b0619b94c1ebdb90e2d7f6'...
Adding participant 'Coopérative'...
Adding participant 'Eleveur Hauteluce'...
Adding participant 'Eleveur Parly'...
Adding participant 'Eleveur Bastia'...
Adding participant 'Laiterie Beaufort'...
Checking if cooperative is in the addressbook: true
Finished!
----
