== Développement d'un smart-contract ```SmartBeaufort```

=== Contexte

Contrairement au smart-contract ```AddressBook``` qui n'est déployé qu'une seule
fois dans la blockchain, nous créerons autant d'instances de
smart-contracts ```SmartBeaufort``` qu'il y aura de _workflows_ à suivre.

A la pratique, nous testerons par facilité et pour une question de productivité
notre code via Truffle et Ganache avant d'envisager un déploiement sur
Quorum / Kaleido.

=== Définition du smart-contract ```SmartBeaufort```

[source,solidity,linenums]
.SmartBeaufort.sol
----
include::../contracts/SmartBeaufort.sol[tag=!implementation]
----
<1> On importe le smart-contract ```AddressBook``` que l'on sollicitera par la
    fonction ```checkGeoBoundaries()```.
<2> *Cette fonctionnalité est donc à développer de votre côté !*
<3> *Cette fonctionnalité est donc à développer de votre côté !*
<4> *Cette fonctionnalité est donc à développer de votre côté !*
<5> Malheureusement Ethereum et Quorum sont très limités en terme de DLT
    comparativement à Fabric & Corda. Dans le cas présent, nous pourrions
    générer le certificat PDF en off-chain et garder un hash du certificat
    au niveau du smart-contract. A ce stade des exercices, nous ne ferons rien
    de plus que cette logique actuelle.
<6> *Cette fonctionnalité est donc à développer de votre côté !*

=== Implémentation du smart-contract ```SmartBeaufort```

Le code de démarrage de cet exercice est disponible dans le repository Git. +
Récupérez ce code et installez les dépendances qui vont bien :

[source,shell]
----
git checkout exercice-02
npm install
----

WARNING: Lancez Ganache (que nous continuons d'utiliser temporairement) ! +
  Si vous l'aviez arrêté précédemment, relancez alors la commande : +
  ```truffle migrate --network ganache --reset``` pour notamment redéployer
  le smart-contract ```AddressBook``` qui est nécessaire.

Commencez par l'implémentation du constructeur et des
fonctions ```sendMilk()```, ```makeCheese()``` et ```checkGeoBoundaries()```.

Vous pourrez vérifier le bon fonctionnement de votre smart-contract en lançant
les tests disponibles :

[source]
----
$ truffle test --network ganache

  Contract: AddressBook
    ✓ should detect geo boundaries properly (258ms)

  Contract: SmartBeaufort
    ✓ should validate geo constraints with proper parties (275ms)
    ✓ should NOT validate geo constraints with non proper parties (248ms)


  3 passing (1s)
----
